apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nfs-mounter
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      name: nfs-mounter
      labels:
        app: nfs-mounter
    spec:
      hostPID: true
      # Temporarily, I think in production we want to give this more time to exit!
      terminationGracePeriodSeconds: 0
      containers:
        - image: gcr.io/mas-datahub/mas-datahub-mounter
          name: nfs-mounter
          env:
          # These two variables changing will restart all the daemonset pods
          - name: FILESERVER
            value: "10.63.240.57"
          - name: MOUNT_PATH
            value: "/mnt/homes"
          securityContext:
            privileged: true
          workingDir: /srv/script
          securityContext:
              privileged: true
