proxy:
  secretToken: "066982e4dd80f3026c85b145daf754a3eeb92c11c82c5b924b9f6b5af635def1"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbgrader
spec:
  #storageClassName: nbgrader-pd-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      name: nbgrader-disk-0
