proxy:
  secretToken: "e7bff733b77309ca273df70e6680e582b0ebf4baf888f73d3d596e90dab019cf"
  https:
    hosts:
      - notebooks.deebul.me
    letsencrypt:
      contactEmail: mhm.wasil@gmail.com
hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']
auth:
  whitelist:
    users:
      - student1
      - student2
  admin:
    users:
      - instructor1
      - instructor2

singleuser:
  defaultUrl: "/lab"
  lifecycleHooks:
    postStart:
      exec:
        command: ["gitpuller", "https://github.com/mhwasil/jupyterhub-kubernetes.git", "master", "mas-materials"]
  memory:
    guarantee: 0.5G
    limit: 0.5G
  #cpu:
  #  limit: 0.5
  #  guarantee: 0.5
  image:
    name : "gcr.io/e2-x-am/singleuser-winter"
    tag : "c664e24"
  storage:
    dynamic:
      storageClass: standard
    capacity: 5Gi
    #type: hostPath
    #extraVolumes:
    #  - name: home
    #    hostPath:
    #      path: /mnt/homes/{username}
    #  - name: nbgrader
    #    hostPath:
    #      path: /mnt/homes/_nbgrader
    #  #- name: newnbgrader1
    #  #  azureFile:
    #  #    secretName: azure-secret
    #  #    shareName: newnbgrader1
    #  #    readOnly: false
    #extraVolumeMounts:
    #  - name: home
    #    mountPath: /home/jovyan
    #  - name: nbgrader
    #    mountPath: /srv/nbgrader
    #  #- name: newnbgrader1
    #  #  mountPath: /srv/.trash
#schedulerStrategy: pack
