proxy:
  secretToken: "e7bff733b77309ca273df70e6680e582b0ebf4baf888f73d3d596e90dab019cf"

singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command: ["gitpuller", "https://github.com/mhwasil/jupyterhub-kubernetes.git", "master", "mas-materials"]
  memory:
    guarantee: 1G
    limit: 1G
  image:
    name: "berkeleydsep/singleuser-data100"
    tag: "ed53a8c"
  storage:
    dynamic:
      storageClass: standard
    capacity: 2Gi
    #type: hostPath
    #extraVolumes:
    #  - name: home
    #    hostPath:
    #      path: /mnt/homes/{username}
    #  - name: nbgrader
    #    hostPath:
    #      path: /mnt/homes/_nbgrader
    #  #- name: newnbgrader1
    #  #  azureFile:
    #  #    secretName: azure-secret
    #  #    shareName: newnbgrader1
    #  #    readOnly: false
    #extraVolumeMounts:
    #  - name: home
    #    mountPath: /home/jovyan
    #  - name: nbgrader
    #    mountPath: /srv/nbgrader
    #  #- name: newnbgrader1
    #  #  mountPath: /srv/.trash
#schedulerStrategy: pack
